# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dev/Proxy_Check

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dev/Proxy_Check/build/Desktop-Release

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/Proxy_Check/build/Desktop-Release/CMakeFiles /home/dev/Proxy_Check/build/Desktop-Release//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/Proxy_Check/build/Desktop-Release/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Proxy_Check

# Build rule for target.
Proxy_Check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Proxy_Check
.PHONY : Proxy_Check

# fast build rule for target.
Proxy_Check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check.dir/build.make CMakeFiles/Proxy_Check.dir/build
.PHONY : Proxy_Check/fast

#=============================================================================
# Target rules for targets named Proxy_Check_autogen_timestamp_deps

# Build rule for target.
Proxy_Check_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Proxy_Check_autogen_timestamp_deps
.PHONY : Proxy_Check_autogen_timestamp_deps

# fast build rule for target.
Proxy_Check_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check_autogen_timestamp_deps.dir/build.make CMakeFiles/Proxy_Check_autogen_timestamp_deps.dir/build
.PHONY : Proxy_Check_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named Proxy_Check_autogen

# Build rule for target.
Proxy_Check_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Proxy_Check_autogen
.PHONY : Proxy_Check_autogen

# fast build rule for target.
Proxy_Check_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check_autogen.dir/build.make CMakeFiles/Proxy_Check_autogen.dir/build
.PHONY : Proxy_Check_autogen/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zlib-build/CMakeFiles/zlib.dir/build.make _deps/zlib-build/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named zlib_autogen_timestamp_deps

# Build rule for target.
zlib_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib_autogen_timestamp_deps
.PHONY : zlib_autogen_timestamp_deps

# fast build rule for target.
zlib_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zlib-build/CMakeFiles/zlib_autogen_timestamp_deps.dir/build.make _deps/zlib-build/CMakeFiles/zlib_autogen_timestamp_deps.dir/build
.PHONY : zlib_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named zlib_autogen

# Build rule for target.
zlib_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zlib_autogen
.PHONY : zlib_autogen

# fast build rule for target.
zlib_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/zlib-build/CMakeFiles/zlib_autogen.dir/build.make _deps/zlib-build/CMakeFiles/zlib_autogen.dir/build
.PHONY : zlib_autogen/fast

#=============================================================================
# Target rules for targets named curl_uninstall

# Build rule for target.
curl_uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curl_uninstall
.PHONY : curl_uninstall

# fast build rule for target.
curl_uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/CMakeFiles/curl_uninstall.dir/build.make _deps/curl-build/CMakeFiles/curl_uninstall.dir/build
.PHONY : curl_uninstall/fast

#=============================================================================
# Target rules for targets named curlu

# Build rule for target.
curlu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curlu
.PHONY : curlu

# fast build rule for target.
curlu/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/lib/CMakeFiles/curlu.dir/build.make _deps/curl-build/lib/CMakeFiles/curlu.dir/build
.PHONY : curlu/fast

#=============================================================================
# Target rules for targets named libcurl_shared

# Build rule for target.
libcurl_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcurl_shared
.PHONY : libcurl_shared

# fast build rule for target.
libcurl_shared/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/lib/CMakeFiles/libcurl_shared.dir/build.make _deps/curl-build/lib/CMakeFiles/libcurl_shared.dir/build
.PHONY : libcurl_shared/fast

#=============================================================================
# Target rules for targets named curlu_autogen_timestamp_deps

# Build rule for target.
curlu_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curlu_autogen_timestamp_deps
.PHONY : curlu_autogen_timestamp_deps

# fast build rule for target.
curlu_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/lib/CMakeFiles/curlu_autogen_timestamp_deps.dir/build.make _deps/curl-build/lib/CMakeFiles/curlu_autogen_timestamp_deps.dir/build
.PHONY : curlu_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named curlu_autogen

# Build rule for target.
curlu_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curlu_autogen
.PHONY : curlu_autogen

# fast build rule for target.
curlu_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/lib/CMakeFiles/curlu_autogen.dir/build.make _deps/curl-build/lib/CMakeFiles/curlu_autogen.dir/build
.PHONY : curlu_autogen/fast

#=============================================================================
# Target rules for targets named libcurl_shared_autogen_timestamp_deps

# Build rule for target.
libcurl_shared_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcurl_shared_autogen_timestamp_deps
.PHONY : libcurl_shared_autogen_timestamp_deps

# fast build rule for target.
libcurl_shared_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/lib/CMakeFiles/libcurl_shared_autogen_timestamp_deps.dir/build.make _deps/curl-build/lib/CMakeFiles/libcurl_shared_autogen_timestamp_deps.dir/build
.PHONY : libcurl_shared_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named libcurl_shared_autogen

# Build rule for target.
libcurl_shared_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcurl_shared_autogen
.PHONY : libcurl_shared_autogen

# fast build rule for target.
libcurl_shared_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/curl-build/lib/CMakeFiles/libcurl_shared_autogen.dir/build.make _deps/curl-build/lib/CMakeFiles/libcurl_shared_autogen.dir/build
.PHONY : libcurl_shared_autogen/fast

#=============================================================================
# Target rules for targets named cpr

# Build rule for target.
cpr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpr
.PHONY : cpr

# fast build rule for target.
cpr/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cpr-build/cpr/CMakeFiles/cpr.dir/build.make _deps/cpr-build/cpr/CMakeFiles/cpr.dir/build
.PHONY : cpr/fast

#=============================================================================
# Target rules for targets named cpr_autogen_timestamp_deps

# Build rule for target.
cpr_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpr_autogen_timestamp_deps
.PHONY : cpr_autogen_timestamp_deps

# fast build rule for target.
cpr_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cpr-build/cpr/CMakeFiles/cpr_autogen_timestamp_deps.dir/build.make _deps/cpr-build/cpr/CMakeFiles/cpr_autogen_timestamp_deps.dir/build
.PHONY : cpr_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named cpr_autogen

# Build rule for target.
cpr_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpr_autogen
.PHONY : cpr_autogen

# fast build rule for target.
cpr_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cpr-build/cpr/CMakeFiles/cpr_autogen.dir/build.make _deps/cpr-build/cpr/CMakeFiles/cpr_autogen.dir/build
.PHONY : cpr_autogen/fast

Proxy_Check_autogen/mocs_compilation.o: Proxy_Check_autogen/mocs_compilation.cpp.o
.PHONY : Proxy_Check_autogen/mocs_compilation.o

# target to build an object file
Proxy_Check_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check.dir/build.make CMakeFiles/Proxy_Check.dir/Proxy_Check_autogen/mocs_compilation.cpp.o
.PHONY : Proxy_Check_autogen/mocs_compilation.cpp.o

Proxy_Check_autogen/mocs_compilation.i: Proxy_Check_autogen/mocs_compilation.cpp.i
.PHONY : Proxy_Check_autogen/mocs_compilation.i

# target to preprocess a source file
Proxy_Check_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check.dir/build.make CMakeFiles/Proxy_Check.dir/Proxy_Check_autogen/mocs_compilation.cpp.i
.PHONY : Proxy_Check_autogen/mocs_compilation.cpp.i

Proxy_Check_autogen/mocs_compilation.s: Proxy_Check_autogen/mocs_compilation.cpp.s
.PHONY : Proxy_Check_autogen/mocs_compilation.s

# target to generate assembly for a file
Proxy_Check_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check.dir/build.make CMakeFiles/Proxy_Check.dir/Proxy_Check_autogen/mocs_compilation.cpp.s
.PHONY : Proxy_Check_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check.dir/build.make CMakeFiles/Proxy_Check.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check.dir/build.make CMakeFiles/Proxy_Check.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check.dir/build.make CMakeFiles/Proxy_Check.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o
.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check.dir/build.make CMakeFiles/Proxy_Check.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i
.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check.dir/build.make CMakeFiles/Proxy_Check.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s
.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Proxy_Check.dir/build.make CMakeFiles/Proxy_Check.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Proxy_Check_autogen"
	@echo "... Proxy_Check_autogen_timestamp_deps"
	@echo "... cpr_autogen"
	@echo "... cpr_autogen_timestamp_deps"
	@echo "... curl_uninstall"
	@echo "... curlu_autogen"
	@echo "... curlu_autogen_timestamp_deps"
	@echo "... libcurl_shared_autogen"
	@echo "... libcurl_shared_autogen_timestamp_deps"
	@echo "... zlib_autogen"
	@echo "... zlib_autogen_timestamp_deps"
	@echo "... Proxy_Check"
	@echo "... cpr"
	@echo "... curlu"
	@echo "... libcurl_shared"
	@echo "... zlib"
	@echo "... Proxy_Check_autogen/mocs_compilation.o"
	@echo "... Proxy_Check_autogen/mocs_compilation.i"
	@echo "... Proxy_Check_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

